name: Desktop Exe

on:
  push:
    branches:
      - master
  workflow_dispatch: { }

jobs:
  build:
    name: Build Windows executable
    runs-on: windows-latest

    env:
      PACKAGE_JAVA_LIBRARY_PATH: ./app/resources

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Set PACKAGE_JAVA_HOME
        run: |
          chcp 65001
          echo ("PACKAGE_JAVA_HOME=" + $env:JAVA_HOME_23_X64) >> $env:GITHUB_ENV

      - name: Build zip and exe
        run: .\gradlew.bat composeApp:packageReleaseExe

      - name: Upload zip artifact
        uses: actions/upload-artifact@v4
        with:
          name: dharmik-windows-release-zip
          path: composeApp/build/outputs/*.zip

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: dharmik-windows-release-exe
          path: composeApp/build/compose/binaries/main-release/exe/*.exe