name: Offline Release

on:
  push:
    branches:
      - dev # change later to master
  workflow_dispatch: { }

jobs:
  build:
    name: Build Beta APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE" | base64 --decode > $GITHUB_WORKSPACE/keystore.jks

      - name: List files in $GITHUB_WORKSPACE
        run: ls -l $GITHUB_WORKSPACE

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
          -Pvariant=offline \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: composeApp/build/outputs/apk/release/composeApp-release.apk