name: Offline Release

on:
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  windows:
    name: Build Windows distribution
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'gradle'

      - name: Package Windows ".exe" distribution
        run: ./gradlew packageReleaseExe -Pvariant=offline

      - name: Rename Artifact
        shell: cmd
        run: |
          setlocal enabledelayedexpansion
          
          set "pattern=dharmik-*.exe"
          set "newName=dharmik.exe"
          set "foundFile="
          
          for /r %%i in (%pattern%) do (
            set "foundFile=%%i"
          )
          
          if defined foundFile (
          echo Renaming !foundFile! to %newName%
            ren "!foundFile!" "%newName%"
          ) else (
            echo No file matching pattern found.
          )
          
          endlocal
          
          echo Successfully renamed file to "dharmik.exe"

      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-exe
          path: composeApp/build/compose/binaries/main-release/exe/*.exe

  android:
    name: Build Android distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Decode Keystore
        env:
          KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
        run: echo "$KEYSTORE_FILE" | base64 --decode > $GITHUB_WORKSPACE/keystore.jks

      - name: List files in $GITHUB_WORKSPACE
        run: ls -l $GITHUB_WORKSPACE

      - name: Build Release APK
        run: |
          ./gradlew assembleRelease \
          -Pvariant=offline \
          -Pandroid.injected.signing.store.file=$GITHUB_WORKSPACE/keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=key0 \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-apk
          path: composeApp/build/outputs/apk/release/composeApp-release.apk